frase = 'Curso em Video Python'
linha = '_'* 60
print(linha)
print('Fatiamento')
print(linha)
print(frase[9])
print(frase[9:13])
print(frase[9:21])
print(frase[9:21:2])
print(frase[:5])
print(frase[15:])
print(frase[9::3])
print(linha)
print('')
print(linha)
print('Análise')
print(linha)
print(len(frase))
print(frase.count('o'))
print(frase.count('o', 0, 13))
print(frase.find('deo'))
print(frase.find('Android'))
print('Curso' in frase)
print(linha)
print('')
print(linha)
print('Transformação')
print(linha)
print(frase.replace('Python','Android'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
frase2 = '  Aprenda Python  '
print(frase2)
print(frase2.strip())
print(frase2.rstrip())
print(frase2.lstrip())
print(linha)
print('')
print(linha)
print('Divisão')
print(linha)
print(frase.split())
frase3 = frase.split()
print('-'.join(frase3))
print(linha)
print('')
print(linha)
print('Praticando')
print(linha)
print(frase)
print(frase[3])
print(frase[3:13])
print(frase[:13])
print(frase[13:])
print(frase[1:15])
print(frase[1:15:2])
print(frase[1::2])
print(frase[::2])
print(frase.count('o'))
print(frase.count('O'))
dividido = frase.split()
print(dividido)
print(dividido[0])
print(dividido[2][3])
