a = input('Digite alguma coisa: ')
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Está em maiúscula? ', a.isupper())
print('Está em minúscula? ', a.islower())
print('Está capitalizada? ', a.istitle())

print('')
print('Utilizando o format')
b = input('Digite mais alguma coisa: ')
print('O tipo primitivo desse valor é: {}' .format(type(b)))
print('Só tem espaços ? {}'.format(b.isspace()))
print('É um número ? {}'.format(b.isnumeric()))
print('É alfabético ? {}' .format(b.isalpha()))
print('É alfanumérico ? {}'.format(b.isalnum()))
print('Está em maiúscula ? {}'.format(b.isupper()))
print('Está em minúscula ? {}'.format(b.islower()))
print('Está capitalizada ? {}'.format(b.istitle()))
